-- AlterTable
ALTER TABLE `Order` ADD COLUMN `adminFee` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    ADD COLUMN `payTotal` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    ADD COLUMN `productQty` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `productTotal` DECIMAL(19, 4) NOT NULL DEFAULT 0,
    ADD COLUMN `shippingFee` DECIMAL(19, 4) NOT NULL DEFAULT 0;
